export type RiskLevel = 'Critical' | 'High' | 'Moderate' | 'Low' | 'Informational';
export type AlertCategory = 'Legal' | 'Compensation' | 'Documentation' | 'Ownership' | 'R&R';
export type LifecycleStage = { name: string; status: 'complete' | 'current' | 'pending'; duration: string; expectedDuration: string; delay: number; authority: string; blockers: string[] };
export type Project = { id: string; name: string; projectCode: string; district: string; phase: string; riskLevel: RiskLevel; riskScore: number; delayProbability: number; predictedDelayWindow: string; confidence: number; lastUpdated: string; budget: number; affectedFamilies: number; lifecycleStages: LifecycleStage[]; contributors: { label: string; value: number }[] };
export type District = { id: string; name: string; monitoredProjects: number; atRiskProjects: number; averageDelay: number; riskRate: number; compensationPending: number; legalCases: number; trend: number[]; mapPosition: { x: number; y: number } };
export type Alert = { id: string; projectId: string; projectName: string; district: string; category: AlertCategory; severity: RiskLevel; predictedDelay: string; confidence: number; primaryCause: string; timestamp: string; recommendedIntervention: string; status: 'Open' | 'Assigned' | 'Monitoring' };
export type RiskAssessment = { category: AlertCategory; score: number; explanation: string; contributors: string[]; affectedProjects: number; recommendedAction: string };
export type Intervention = { id: string; title: string; owner: string; status: 'Open' | 'In progress' | 'Complete'; dueDate: string; assignedAt: string; projectId: string };
export type FinancialRecord = { district: string; sanctioned: number; released: number; utilized: number; pendingCompensation: number; agingBuckets: number[] };
export type PolicyBriefing = { scope: string; generatedAt: string; freshness: string; confidence: number; sections: string[] };
export type Benchmark = { metric: string; period: string; sampleSize: number; values: { label: string; value: number; rank: number; percentile: number; trend: number }[] };
export type Corridor = { id: string; name: string; code: string; route: string; riskLevel: RiskLevel; riskScore: number; projects: number; exposedValue: number; leadSignal: string; nodes: { label: string; x: number; y: number; projectId?: string; riskLevel: RiskLevel }[] };
export type Permission = { key: string; label: string; description: string; state: 'Granted' | 'Restricted' };
export type Role = { name: string; scope: string; users: number; description: string; permissions: Permission[] };
export type SessionTrust = { device: string; location: string; lastVerified: string; assurance: string; expires: string };
export type AuditEntry = { id: string; timestamp: string; actor: string; role: string; action: string; resource: string; status: 'Success' | 'Review' | 'Blocked'; detail: string };

const stages = (current: string, blocker: string): LifecycleStage[] => [
  { name: 'Preliminary notification', status: 'complete', duration: '28d', expectedDuration: '30d', delay: -2, authority: 'Revenue Department', blockers: [] },
  { name: 'Social impact assessment', status: current === 'SIA' ? 'current' : 'complete', duration: current === 'SIA' ? '64d' : '58d', expectedDuration: '60d', delay: current === 'SIA' ? 4 : -2, authority: 'District Collector', blockers: current === 'SIA' ? [blocker] : [] },
  { name: 'Award & compensation', status: current === 'Award' ? 'current' : current === 'SIA' ? 'pending' : 'complete', duration: current === 'Award' ? '126d' : current === 'SIA' ? '—' : '84d', expectedDuration: '90d', delay: current === 'Award' ? 36 : -6, authority: 'Special LAO', blockers: current === 'Award' ? [blocker] : [] },
  { name: 'Possession & handover', status: current === 'Possession' ? 'current' : 'pending', duration: current === 'Possession' ? '37d' : '—', expectedDuration: '45d', delay: current === 'Possession' ? -8 : 0, authority: 'Project Director', blockers: current === 'Possession' ? [blocker] : [] },
];

export const projects: Project[] = [
  { id: 'p-001', name: 'Dholera–Ahmedabad Connector', projectCode: 'DAC/GJ/14', district: 'Ahmedabad', phase: 'Possession & handover', riskLevel: 'Low', riskScore: 24, delayProbability: 18, predictedDelayWindow: 'On track', confidence: 89, lastUpdated: '12 min ago', budget: 890, affectedFamilies: 430, contributors: [{ label: 'Residual cases', value: 34 }, { label: 'Utility shifting', value: 26 }, { label: 'Documentation', value: 18 }, { label: 'Other', value: 22 }], lifecycleStages: stages('Possession', '3 residual cases') },
  { id: 'p-002', name: 'Mumbai–Ahmedabad High-Speed Rail · GJ-2', projectCode: 'MAHSR/GJ/02', district: 'Anand', phase: 'Award & compensation', riskLevel: 'High', riskScore: 69, delayProbability: 64, predictedDelayWindow: '4–7 months', confidence: 86, lastUpdated: '28 min ago', budget: 1260, affectedFamilies: 920, contributors: [{ label: 'Compensation pendency', value: 42 }, { label: 'Land records', value: 25 }, { label: 'R&R readiness', value: 19 }, { label: 'Other', value: 14 }], lifecycleStages: stages('Award', '214 awards pending payment') },
  { id: 'p-003', name: 'Delhi–Mumbai Expressway · Gujarat Package', projectCode: 'DME/GJ/07', district: 'Bharuch', phase: 'Social impact assessment', riskLevel: 'Moderate', riskScore: 49, delayProbability: 42, predictedDelayWindow: '2–4 months', confidence: 78, lastUpdated: '1 hr ago', budget: 742, affectedFamilies: 610, contributors: [{ label: 'Record mismatch', value: 36 }, { label: 'Absent claimants', value: 24 }, { label: 'R&R readiness', value: 22 }, { label: 'Other', value: 18 }], lifecycleStages: stages('SIA', 'Village register reconciliation') },
  { id: 'p-004', name: 'Western Dedicated Freight Corridor · Package 8', projectCode: 'WDFC/GJ/08', district: 'Kutch', phase: 'Award & compensation', riskLevel: 'Critical', riskScore: 84, delayProbability: 79, predictedDelayWindow: '8–12 months', confidence: 92, lastUpdated: '2 hr ago', budget: 488, affectedFamilies: 1180, contributors: [{ label: 'Title disputes', value: 38 }, { label: 'Compensation pendency', value: 31 }, { label: 'Legal stays', value: 19 }, { label: 'Other', value: 12 }], lifecycleStages: stages('Award', '87 survey numbers under legal review') },
  { id: 'p-005', name: 'Surat Metro · North–South Extension', projectCode: 'SM/NSE/GJ', district: 'Surat', phase: 'Documentation review', riskLevel: 'Moderate', riskScore: 43, delayProbability: 37, predictedDelayWindow: '2–4 months', confidence: 81, lastUpdated: '3 hr ago', budget: 384, affectedFamilies: 260, contributors: [{ label: 'Ownership', value: 41 }, { label: 'Utility shifting', value: 24 }, { label: 'Records', value: 21 }, { label: 'Other', value: 14 }], lifecycleStages: stages('SIA', '17 co-owner records pending') },
];

export const districts: District[] = [
  { id: 'd-01', name: 'Kutch', monitoredProjects: 14, atRiskProjects: 7, averageDelay: 6.4, riskRate: 50, compensationPending: 22.8, legalCases: 31, trend: [31, 34, 38, 43, 48, 50], mapPosition: { x: 19, y: 39 } },
  { id: 'd-02', name: 'Bharuch', monitoredProjects: 12, atRiskProjects: 5, averageDelay: 4.6, riskRate: 41.7, compensationPending: 16.2, legalCases: 24, trend: [27, 30, 33, 35, 39, 42], mapPosition: { x: 47, y: 69 } },
  { id: 'd-03', name: 'Surat', monitoredProjects: 18, atRiskProjects: 6, averageDelay: 3.2, riskRate: 33.3, compensationPending: 12.8, legalCases: 19, trend: [29, 28, 31, 30, 32, 33], mapPosition: { x: 51, y: 84 } },
  { id: 'd-04', name: 'Ahmedabad', monitoredProjects: 23, atRiskProjects: 3, averageDelay: 1.8, riskRate: 13, compensationPending: 4.1, legalCases: 11, trend: [19, 17, 16, 15, 14, 13], mapPosition: { x: 35, y: 49 } },
  { id: 'd-05', name: 'Vadodara', monitoredProjects: 16, atRiskProjects: 4, averageDelay: 2.7, riskRate: 25, compensationPending: 8.4, legalCases: 15, trend: [21, 24, 22, 26, 25, 25], mapPosition: { x: 55, y: 58 } },
  { id: 'd-06', name: 'Rajkot', monitoredProjects: 11, atRiskProjects: 3, averageDelay: 3.1, riskRate: 27.3, compensationPending: 6.9, legalCases: 13, trend: [18, 20, 22, 24, 26, 27], mapPosition: { x: 30, y: 57 } },
  { id: 'd-07', name: 'Anand', monitoredProjects: 9, atRiskProjects: 2, averageDelay: 2.2, riskRate: 22.2, compensationPending: 3.8, legalCases: 7, trend: [20, 19, 20, 21, 22, 22], mapPosition: { x: 48, y: 58 } },
  { id: 'd-08', name: 'Mehsana', monitoredProjects: 10, atRiskProjects: 2, averageDelay: 1.9, riskRate: 20, compensationPending: 3.2, legalCases: 8, trend: [23, 22, 21, 20, 20, 20], mapPosition: { x: 39, y: 34 } },
];

export const alerts: Alert[] = [
  { id: 'a-01', projectId: 'p-004', projectName: 'Western Dedicated Freight Corridor · Package 8', district: 'Kutch', category: 'Legal', severity: 'Critical', predictedDelay: '8–12 months', confidence: 92, primaryCause: '87 survey numbers remain under title review', timestamp: '12 min ago', recommendedIntervention: 'Convene district title-clearing cell and publish a 14-day resolution docket', status: 'Open' },
  { id: 'a-02', projectId: 'p-002', projectName: 'Mumbai–Ahmedabad High-Speed Rail · GJ-2', district: 'Anand', category: 'Compensation', severity: 'High', predictedDelay: '4–7 months', confidence: 86, primaryCause: '214 awards have crossed the 60-day payment threshold', timestamp: '28 min ago', recommendedIntervention: 'Release the verified tranche and schedule a beneficiary payment camp', status: 'Assigned' },
  { id: 'a-03', projectId: 'p-003', projectName: 'Delhi–Mumbai Expressway · Gujarat Package', district: 'Bharuch', category: 'Documentation', severity: 'Moderate', predictedDelay: '2–4 months', confidence: 78, primaryCause: 'Village register reconciliation is behind the SIA critical path', timestamp: '1 hr ago', recommendedIntervention: 'Deploy the district record reconciliation cell for two weeks', status: 'Monitoring' },
  { id: 'a-04', projectId: 'p-005', projectName: 'Surat Metro · North–South Extension', district: 'Surat', category: 'Ownership', severity: 'Moderate', predictedDelay: '2–4 months', confidence: 81, primaryCause: '17 co-owner records require partition validation', timestamp: '2 hr ago', recommendedIntervention: 'Start pre-award mediation in the three priority villages', status: 'Open' },
  { id: 'a-05', projectId: 'p-001', projectName: 'Dholera–Ahmedabad Connector', district: 'Ahmedabad', category: 'R&R', severity: 'Low', predictedDelay: '1–2 months', confidence: 72, primaryCause: 'Three residual cases have moved the handover date', timestamp: '3 hr ago', recommendedIntervention: 'Confirm site readiness with the R&R authority', status: 'Open' },
];

export const interventions: Intervention[] = [
  { id: 'i-01', title: 'Clear Kutch title review docket', owner: 'Legal Cell — Kutch', status: 'Open', dueDate: '18 Jun 2025', assignedAt: 'Today, 09:42', projectId: 'p-004' },
  { id: 'i-02', title: 'Release verified compensation tranche', owner: 'Finance — Anand', status: 'In progress', dueDate: '22 Jun 2025', assignedAt: 'Yesterday, 16:10', projectId: 'p-002' },
  { id: 'i-03', title: 'Reconcile Bharuch village registers', owner: 'Records — Bharuch', status: 'In progress', dueDate: '26 Jun 2025', assignedAt: '10 Jun 2025', projectId: 'p-003' },
];
export const financials: FinancialRecord[] = [
  { district: 'Kutch', sanctioned: 488, released: 318, utilized: 271, pendingCompensation: 22.8, agingBuckets: [12, 10, 7, 4] },
  { district: 'Bharuch', sanctioned: 742, released: 538, utilized: 462, pendingCompensation: 16.2, agingBuckets: [8, 6, 4, 2] },
  { district: 'Surat', sanctioned: 384, released: 318, utilized: 291, pendingCompensation: 12.8, agingBuckets: [7, 5, 3, 1] },
  { district: 'Ahmedabad', sanctioned: 890, released: 834, utilized: 802, pendingCompensation: 4.1, agingBuckets: [4, 3, 2, 1] },
  { district: 'Vadodara', sanctioned: 516, released: 438, utilized: 391, pendingCompensation: 8.4, agingBuckets: [6, 5, 3, 2] },
];
export const assessments: RiskAssessment[] = [
  { category: 'Compensation', score: 72, explanation: 'Payment velocity has slowed for a third consecutive fortnight, concentrated in Kutch, Anand and Bharuch.', contributors: ['1,831 pending awards', '18% accounts need validation', 'Median payment age: 76 days'], affectedProjects: 14, recommendedAction: 'Prioritise tranche release and payment camps' },
  { category: 'Legal', score: 58, explanation: 'New title reviews in three Gujarat projects are creating critical-path exposure, while response capacity remains stable.', contributors: ['31 active cases', '8 new filings this month', '67% matters have response filed'], affectedProjects: 9, recommendedAction: 'Escalate cases with >90-day hearing gap' },
  { category: 'Documentation', score: 64, explanation: 'Record mismatch is the earliest leading indicator across survey-to-award transitions.', contributors: ['14 villages affected', '3.8% title mismatch rate', '18 days average rework'], affectedProjects: 11, recommendedAction: 'Deploy district record reconciliation cells' },
  { category: 'Ownership', score: 43, explanation: 'Ownership complexity is moderate; concentrated pockets need early mediation in Surat and Rajkot.', contributors: ['2,104 co-owners', '11% unresolved partitions', '4 mediation panels active'], affectedProjects: 7, recommendedAction: 'Start pre-award mediation in priority villages' },
  { category: 'R&R', score: 37, explanation: 'Resettlement readiness is improving, with isolated handover risk in Ahmedabad and Vadodara.', contributors: ['82% sites ready', '9 facilities pending', '3 handover dates moved'], affectedProjects: 5, recommendedAction: 'Lock site handover dates with district PMUs' },
];
export const benchmarks: Benchmark[] = [
  { metric: 'Average delay (months)', period: 'Q2 FY25', sampleSize: 68, values: [{ label: 'Ahmedabad', value: 1.8, rank: 1, percentile: 91, trend: -12 }, { label: 'Anand', value: 2.2, rank: 2, percentile: 82, trend: -4 }, { label: 'Vadodara', value: 2.7, rank: 3, percentile: 71, trend: 6 }, { label: 'Surat', value: 3.2, rank: 4, percentile: 62, trend: 4 }, { label: 'Kutch', value: 6.4, rank: 5, percentile: 28, trend: 14 }] },
  { metric: 'Compensation release rate', period: 'Q2 FY25', sampleSize: 68, values: [{ label: 'Ahmedabad', value: 93.7, rank: 1, percentile: 95, trend: 3 }, { label: 'Anand', value: 88.2, rank: 2, percentile: 81, trend: 2 }, { label: 'Vadodara', value: 84.0, rank: 3, percentile: 72, trend: -5 }, { label: 'Surat', value: 82.8, rank: 4, percentile: 68, trend: -2 }, { label: 'Kutch', value: 65.2, rank: 5, percentile: 29, trend: -11 }] },
];
export const briefing: PolicyBriefing = { scope: 'All monitored Gujarat projects', generatedAt: '12 Jun 2025, 10:42 IST', freshness: 'Demo data through 11 Jun 2025', confidence: 88, sections: ['Executive signal', 'District hotspots', 'Compensation exposure', 'Legal and documentation watch', 'Recommended decisions'] };
export const corridors: Corridor[] = [
  { id: 'c-01', name: 'Western Dedicated Freight Corridor', code: 'WDFC/GJ', route: 'Kutch → Mehsana → Ahmedabad → Bharuch', riskLevel: 'Critical', riskScore: 84, projects: 8, exposedValue: 1240, leadSignal: 'Title review backlog', nodes: [{ label: 'Kutch', x: 17, y: 38, projectId: 'p-004', riskLevel: 'Critical' }, { label: 'Mehsana', x: 39, y: 33, riskLevel: 'Low' }, { label: 'Ahmedabad', x: 35, y: 49, riskLevel: 'Low' }, { label: 'Bharuch', x: 47, y: 70, riskLevel: 'High' }] },
  { id: 'c-02', name: 'Mumbai–Ahmedabad High-Speed Rail', code: 'MAHSR/GJ', route: 'Ahmedabad → Anand → Surat', riskLevel: 'High', riskScore: 69, projects: 6, exposedValue: 980, leadSignal: 'Compensation aging', nodes: [{ label: 'Ahmedabad', x: 35, y: 49, projectId: 'p-002', riskLevel: 'Low' }, { label: 'Anand', x: 48, y: 58, projectId: 'p-002', riskLevel: 'High' }, { label: 'Surat', x: 51, y: 84, riskLevel: 'Moderate' }] },
  { id: 'c-03', name: 'Dholera SIR Connector', code: 'DSC/GJ', route: 'Ahmedabad → Dholera', riskLevel: 'Low', riskScore: 24, projects: 4, exposedValue: 620, leadSignal: 'Residual cases', nodes: [{ label: 'Ahmedabad', x: 35, y: 49, projectId: 'p-001', riskLevel: 'Low' }, { label: 'Dholera', x: 30, y: 66, riskLevel: 'Low' }] },
];
export const roles: Role[] = [
  { name: 'State Control Room', scope: 'Gujarat · all districts', users: 12, description: 'State-level monitoring, intervention assignment and briefing access.', permissions: [{ key: 'view', label: 'View intelligence', description: 'Read portfolio, district and project signals', state: 'Granted' }, { key: 'assign', label: 'Assign interventions', description: 'Route actions to district owners', state: 'Granted' }, { key: 'export', label: 'Export briefings', description: 'Create signed briefing packages', state: 'Granted' }, { key: 'access', label: 'Manage access', description: 'Change roles and access scopes', state: 'Restricted' }] },
  { name: 'District Program Unit', scope: 'Assigned district only', users: 34, description: 'Field execution role for district collectors and PMUs.', permissions: [{ key: 'view', label: 'View intelligence', description: 'Read assigned district signals', state: 'Granted' }, { key: 'assign', label: 'Assign interventions', description: 'Accept and track local actions', state: 'Granted' }, { key: 'export', label: 'Export briefings', description: 'Export district summaries', state: 'Restricted' }, { key: 'access', label: 'Manage access', description: 'Change roles and access scopes', state: 'Restricted' }] },
];
export const sessionTrust: SessionTrust = { device: 'Managed workstation · Chrome 124', location: 'Gandhinagar, Gujarat · State network', lastVerified: '12 Jun 2025 · 10:38 IST', assurance: 'AAL2 · MFA verified', expires: '12 Jun 2025 · 18:00 IST' };
export const auditEntries: AuditEntry[] = [
  { id: 'au-001', timestamp: '12 Jun 2025 · 10:42:18', actor: 'R. K. Shah', role: 'State Control Room', action: 'Generated policy briefing', resource: 'BRF-GJ-250612-01', status: 'Success', detail: 'Portfolio briefing generated for all monitored Gujarat projects at 88% model confidence.' },
  { id: 'au-002', timestamp: '12 Jun 2025 · 10:31:04', actor: 'Meera Joshi', role: 'District Program Unit', action: 'Accepted intervention', resource: 'INT-KUTCH-004', status: 'Success', detail: 'Title-clearing docket accepted by Legal Cell — Kutch; due 18 Jun 2025.' },
  { id: 'au-003', timestamp: '12 Jun 2025 · 09:58:46', actor: 'R. K. Shah', role: 'State Control Room', action: 'Export requested', resource: 'WDFC/GJ/08', status: 'Review', detail: 'Export contains project-level affected-family data and requires second-person review.' },
  { id: 'au-004', timestamp: '11 Jun 2025 · 17:22:10', actor: 'System policy', role: 'Access service', action: 'Permission change blocked', resource: 'ROLE-DPU-07', status: 'Blocked', detail: 'Attempted scope change was outside the signed-in State Control Room permission boundary.' },
  { id: 'au-005', timestamp: '11 Jun 2025 · 16:04:39', actor: 'Arjun Patel', role: 'District Program Unit', action: 'Viewed project record', resource: 'DME/GJ/07', status: 'Success', detail: 'Project 360 record opened from the Bharuch district diagnostics view.' },
];
export const getProject = (id?: string) => projects.find((project) => project.id === id) ?? projects[0];